Job_Search_MVC_Application/Controllers/AddJobController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Job_Search_MVC_Application.Models;

namespace Job_Search_MVC_Application.Controllers
{
    public class AddJobController : Controller
    {
        Job_Search_MVCEntities dbobj = new Job_Search_MVCEntities();
        // GET: AddJob
        public ActionResult AddJob_PageLoad()
        {
            return View();
        }
        public ActionResult addjob_click(JobAdd clsobj)
        {
            if (ModelState.IsValid)
            {
                int cid = Convert.ToInt32(Session["uid"]);

                dbobj.sp_Job_Insert(cid, clsobj.jobname, clsobj.numofvacancy, clsobj.reqskills, clsobj.jobdescription, clsobj.salary, clsobj.qualifi, clsobj.jstatus, clsobj.entrydate, clsobj.lastappldate);
                clsobj.msg = "insert successfully";
            }
             
                return View("AddJob_PageLoad", clsobj);
            
        }
    }
}

Job_Search_MVC_Application/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Job_Search_MVC_Application.Models;

namespace Job_Search_MVC_Application.Controllers
{
    public class LoginController : Controller
    {
        Job_Search_MVCEntities dbobj = new Job_Search_MVCEntities();
        // GET: Login
        public ActionResult Login_Pageload()
        {
            return View();
        }
        public ActionResult UserHomePage()
        {
            return View();
        }
        public ActionResult AdminCompanyHomePage()
        {
            return View();
        }
        public ActionResult Login_Click(Login clsobj)
        {
            if (ModelState.IsValid)
            {
                ObjectParameter op = new ObjectParameter("status", typeof(int));
                dbobj.sp_Login(clsobj.Username, clsobj.Password, op);
                int val = Convert.ToInt32(op.Value);
                if (val == 1)
                {
                    var uid = dbobj.sp_GetLoginId(clsobj.Username, clsobj.Password).FirstOrDefault();
                    Session["uid"] = uid;

                    var LogType = dbobj.sp_GetLoginType(clsobj.Username, clsobj.Password).FirstOrDefault();
                    if (LogType == "user")
                    {
                        return RedirectToAction("UserHomePage");
                    }
                    else if (LogType == "admin")
                    {
                        return RedirectToAction("AdminCompanyHomePage");
                    }

                }
                else
                {
                    ModelState.Clear();
                    clsobj.msg = "Invalid Login";
                    return View("Login_Pageload", clsobj);
                }
            }
            return View("Login_Pageload", clsobj);

        }

        public ActionResult Index()
        {
            return View();
        }
    }
}

Job_Search_MVC_Application/Views/AddJob/AddJob_PageLoad.cshtml
@model Job_Search_MVC_Application.Models.JobAdd
@{
    ViewBag.Title = "AddJob_PageLoad";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>AddJob</h2>
@using (Html.BeginForm("addjob_click", "AddJob", FormMethod.Post))
{
    <div>
        <label>Jobname</label>
    </div>
    <div>
        @Html.TextBoxFor(m => m.jobname)
    </div>

    <div>
        <label>Number of vacancy</label>
    </div>
    <div>
        @Html.TextBoxFor(m => m.numofvacancy)
    </div>

    <div>
        <label>Required Skills</label>
    </div>
    <div>
        @Html.TextBoxFor(m => m.reqskills)
    </div>

    <div>
        <label>Job Description</label>
    </div>
    <div>
        @Html.TextBoxFor(m => m.jobdescription)
    </div>

    <div>
        <label>Salary</label>
    </div>
    <div>
        @Html.TextBoxFor(m => m.salary)
    </div>
    <div>
        <label>Qualification</label>
    </div>
    <div>
        @Html.TextBoxFor(m => m.qualifi)
    </div>
    <div>
        <label>Job Status</label>
    </div>
    <div>
        @Html.TextBoxFor(m => m.jstatus)
    </div>

    <div>
        <label>Entry Date</label>
    </div>
    <div>
        @Html.TextBoxFor(m => m.entrydate)
    </div>

    <div>
        <label>Last apply Date</label>
    </div>
    <div>
        @Html.TextBoxFor(m => m.lastappldate)
    </div>

    <div>
        <input type="submit" value="Insert" />
        @Html.DisplayFor(m => m.msg)
    </div>
    <div>
        <ul>
            <li>@Html.ActionLink("Back to Home", "AdminCompanyHomePage", "Login")</li>
        </ul>
    </div>

}