Job_Search_MVC_Application/Controllers/CompanyRegController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Job_Search_MVC_Application.Models;

namespace Job_Search_MVC_Application.Controllers
{
    public class CompanyRegController : Controller
    {
        Job_Search_MVCEntities dbobj = new Job_Search_MVCEntities();
        // GET: CompanyReg

        public ActionResult InsertCompany_Pageload()
        {
            return View();
        }
        public ActionResult InsertCompany_click(CompanyRegister clsobj)
        {
            if (ModelState.IsValid)
            {
                var getmaxid = dbobj.sp_GetMaxIdLogin().FirstOrDefault();
                int mid = Convert.ToInt32(getmaxid);
                int regid = 0;
                if (mid == 0)
                {
                    regid = 1;
                }
                else
                {
                    regid = mid + 1;
                }
                //get
                dbobj.sp_CompanyRegister(regid, clsobj.ComName, clsobj.ComAddress, clsobj.ComPhone, clsobj.ComEmail,"active");
                dbobj.sp_LoginInsert(regid, clsobj.Username, clsobj.Password, "admin","active");
                clsobj.ComMsg = "successfully inserted";

            }
            return View("InsertCompany_Pageload", clsobj);
        }
        public ActionResult Index()
        {
            return View();
        }
    }
}

Job_Search_MVC_Application/Controllers/UserRegController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Job_Search_MVC_Application.Models;

namespace Job_Search_MVC_Application.Controllers
{
    public class UserRegController : Controller
    {
        Job_Search_MVCEntities dbobj = new Job_Search_MVCEntities();
        // GET: UserReg
        public ActionResult UserInsert_Pageload()
        {

            return View();
        }

        public ActionResult UserInsert_Click(UserRegister clsobj)
        {
            if (ModelState.IsValid)
            {
                
                var getmaxid = dbobj.sp_GetMaxIdLogin().FirstOrDefault();
                int mid = Convert.ToInt32(getmaxid);
                int regid = 0;
                if (mid == 0)
                {
                    regid = 1;
                }
                else
                {
                    regid = mid + 1;
                }
                //get
                dbobj.sp_UserRegister(regid, clsobj.UsName, clsobj.UsAge, clsobj.UsAddress, clsobj.UsPhone, clsobj.UsEmail,clsobj.UsPincode,clsobj.UsState,clsobj.UsDist,clsobj.UsQual,clsobj.UsSkills,clsobj.UsExp,"active");
                dbobj.sp_LoginInsert(regid, clsobj.Username, clsobj.Password, "user","active");
                clsobj.Usermsg = "successfully inserted";

            }
            return View("UserInsert_Pageload", clsobj);
        }
        public ActionResult Index()
        {
            return View();
        }
    }
}

Job_Search_MVC_Application/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Job Search", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @*<li>@Html.ActionLink("About", "About", "Home")</li>*@
                    <li>@Html.ActionLink("Login", "Login_Pageload", "Login")</li>
                    <li>@Html.ActionLink("User Registration", "UserInsert_Pageload", "UserReg")</li>
                    <li>@Html.ActionLink("Company Register", "InsertCompany_Pageload", "CompanyReg")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>